---
apache_public_folder: "public"

apache_packages:
    - libapache2-mod-php
    
apache_modules:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

apache_conf_custom: false
apache_conf_enable: false
apache_conf_disable: false

apache_virtual_host: false