---
php_ppa: ondrej/php
php_version: 7.1
php_versions: 
    - 7.1
php_modules: 
    - mbstring
    - mcrypt
    - mysql
    - gd
    - intl
    - curl
    - xml
    - zip
php_config_dirs: ['cli', 'apache2', 'fpm']

php_config: {}