---
php_installed: true
php_ppa: ondrej/php
php_version: 7.1
php_versions: 
    - 7.1

php_modules: 
    - mbstring
    - mcrypt
    - mysql
    - gd
    - intl
    - curl
    - xml
    - zip
    
php_config_dirs: ['cli']

php_config: {}

# PHP Mode
# 'fastcgi' = will use libapache2-mod-fastcgi 
# 'module' will use libapache2-mod-php{{php version}}
#  Nginx always use fastcgi
php_mode: "module" 
