---
- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  tags: composer

- name: install composer
  become: true
  shell: cat /tmp/installer | php -- --install-dir={{ composer_install_dir }}
  args:
    creates: "{{ composer_install_dir }}/composer"
  tags: composer

- name: rename composer.phar to composer
  become: true
  shell: mv {{ composer_install_dir }}/composer.phar {{ composer_install_dir }}/composer
  args:
    creates: "{{ composer_install_dir }}/composer"
  tags: composer


- name: make composer executable
  become: true
  tags: composer file
  file:
    path: "{{ composer_install_dir }}/composer"
    state: file
    mode: a+x
  
- name: update to the latest version
  become: true
  command: >
    {{ composer_install_dir }}/composer self-update
  register: composer_self_update_out
  changed_when: "'Updating to version' in composer_self_update_out.stderr"
  when: composer_self_update
  tags: composer
    