---
# Install libapache2-mod-php for all the versions

- name: Install Apache Mode PHP Packages
  become: true
  apt: pkg="libapache2-mod-php{{item}}" state=latest
  with_items: "{{php_versions}}"
  when: php_mode == 'module'
  
- name: Adding apache2 in the config dirs
  set_fact:
    php_config_dirs: "{{ php_config_dirs + ['apache2']}}"
