---
#- debug:
#    msg: "PPA {{ php_ppa }} "
    
- name: Add ppa Repository
  become: true
  apt_repository: repo="ppa:{{php_ppa}}"

- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install PHP Versions
  become: true
  apt: pkg="php{{item}}" state=latest
  with_items: "{{php_versions}}"
  
- name: Install PHP Modules
  become: true
  apt: pkg="php{{item[0]}}-{{item[1]}}" state=latest
  when: php_modules is defined
  with_nested:
    - "{{php_versions}}"
    - "{{php_modules}}"
    
# always nuke the file.
- name: Create/ Reset PHP Ini Options
  become: true
  copy:
    content: ""
    dest: "/etc/php/{{item[1]}}/{{item[0]}}/conf.d/99-custom.ini"
    force: yes
    owner: root
    mode: 0644
  with_nested:
    - ["cli", "apache2"]
    - "{{php_versions}}"

#- name: Debug
#  debug:
#    msg: "/etc/php/{{item[1]}}/{{item[0]}}/conf.d/99-custom.ini"
#  with_nested:
#    - ["cli", "apache2"]
#    - "{{php_versions}}"
      
- name: Configure PHP
  become: true
  ini_file:
    create: true
    owner: root
    mode: 0555
    path: "/etc/php/{{item[1]}}/{{item[0]}}/conf.d/99-custom.ini"
    section: "{{item[2].section}}"
    option: "{{item[2].key}}"
    value: "{{item[2].value}}"

  with_nested:
    - ["cli", "apache2"]
    - "{{php_versions}}"
    - "{{php_ini}}"
      
- name: Install PHP Switcher - Create target directory
  file: 
    path: /home/vagrant/scripts
    state: directory
    owner: vagrant
  
- name: Install PHP Switcher
  template: 
    src: phpSwitcher.sh 
    dest: /home/vagrant/scripts/phpSwitcher
    owner: vagrant
    mode: "a+x"
    
- name: Switch To PHP {{php_version}}
  command: /home/vagrant/scripts/phpSwitcher {{php_version}}