---
#- debug:
#    msg: "PPA {{ php_ppa }} "
    
- name: Add ppa Repository
  become: true
  apt_repository: repo="ppa:{{php_ppa}}"

- name: Update apt
  become: true
  apt: update_cache=yes


# Install PHP version with -cli so apache modules are not enabled by default
- name: Install PHP Versions
  become: true
  apt: pkg="php{{item}}-cli" state=latest
  with_items: "{{php_versions}}"
  
# Depending on php mode 
# If Nginx - make sure php-fpm module is insalled 
# If Apache - we want to install libapache2-mod-php if run as module or libapache2-mod-fastcgi if run as CGI
- include: "{{item}}.yml"
  with_items: "{{ apache_installed is defined | ternary( 'apache-' + php_mode,  nginx_installed is defined | ternary('nginx', False)  ) }}" 

# Install PHP  Modules
- name: Install Extra PHP Modules
  become: true
  apt: pkg="php{{item[0]}}-{{item[1]}}" state=latest
  when: php_modules is defined
  with_nested:
    - "{{php_versions}}"
    - "{{php_modules}}"
 
# PHP Configuration 
- name: Create the configurations files
  become: true
  template:
    src: config.conf.tpl
    dest: "/etc/php/{{item[0]}}/{{item[1]}}/conf.d/99-custom.ini"
  vars:
    config: "{{php_config}}"
  with_nested:
    - "{{php_versions}}" 
    - "{{php_config_dirs}}"
  notify:
    - php config changed
  

    