---
#- debug:
#    msg: "PPA {{ php_ppa }} "
    
- name: Add ppa Repository
  become: true
  apt_repository: repo="ppa:{{php_ppa}}"

- name: Update apt
  become: true
  apt: update_cache=yes


# Install PHP version with -cli so apache modules are not enabled by default
- name: Install PHP Versions
  become: true
  apt: pkg="php{{item}}-cli" state=latest
  with_items: "{{php_versions}}"
  
# If Apache - we want to install "libapache2-mod-php{{version}}"
- name: Install Apache PHP Modules
  become: true
  apt: pkg="libapache2-mod-php{{item}}" state=latest
  with_items: "{{php_versions}}"
  when: apache_installed is defined
  
# Install PHP  Modules
- name: Install PHP Modules
  become: true
  apt: pkg="php{{item[0]}}-{{item[1]}}" state=latest
  when: php_modules is defined
  with_nested:
    - "{{php_versions}}"
    - "{{php_modules}}"
 
 
# PHP Configuration 
- name: Create the configurations file
  become: true
  template:
    src: config.conf.tpl
    dest: "/etc/php/{{item[0]}}/{{item[1]}}/conf.d/99-custom.ini"
  vars:
    config: "{{php_config}}"
  with_nested:
    - "{{php_versions}}" 
    - "{{php_config_dirs}}"
  notify:
    - php config changed
  

    