---
# Add FPM folder in the config variable
- name: Setting Php Config Dirs
  set_fact:
    php_config_dirs: "{{ php_config_dirs + ['fpm']}}"
    
- name: Install php-fpm
  become: true
  apt: pkg="php{{version}}-fpm" state=latest
  with_items: "{{php_versions}}"
  loop_control:
    loop_var: version